# This file is generated by tools/bundle_ghpython.py.
# Edit src/ice_crack/source/*.py, then run the bundler again.

# --- src/ice_crack/source/header.py ---
"""
Recursive ice crack surface splitter for Grasshopper.

Inputs:
    surface: Planar Surface, Brep, BrepFace, or closed planar Curve
    config: Optional multiline config string
    config_text: Optional multiline config string alias
    config_path: Optional path to a text config file
    min_area: Smallest piece area before recursion stops
    max_depth: Maximum recursive split depth
    seed: Random seed for repeatable cracks
    crack_variation: Randomness from 0.0 to 1.0 along selected sides
    tol: Optional model tolerance override

Config format:
    min_area=1.0
    max_depth=8
    seed=1
    crack_variation=0.25
    tol=None

Outputs:
    A: Cracked surface pieces
    B: Crack curves used for successful splits
    C: Final piece areas
    message: Status message
"""

# --- src/ice_crack/source/config.py ---
DEFAULT_CONFIG = {
    "min_area": 1.0,
    "max_depth": 8,
    "seed": 1,
    "crack_variation": 0.25,
    "tol": None,
}

CONFIG_TYPES = {
    "min_area": float,
    "max_depth": int,
    "seed": int,
    "crack_variation": float,
    "tol": float,
}


def parse_config_value(key, value):
    value = str(value).strip()

    if key == "tol" and value.lower() in ("", "none", "null"):
        return None

    return CONFIG_TYPES[key](value)


def parse_config_text(text):
    values = {}
    errors = []

    if not text:
        return values, errors

    for line_number, raw_line in enumerate(str(text).splitlines(), 1):
        line = raw_line.strip()

        if not line or line.startswith("#"):
            continue

        if "=" in line:
            key, value = line.split("=", 1)
        elif ":" in line:
            key, value = line.split(":", 1)
        else:
            errors.append("Line {} has no '=' or ':'.".format(line_number))
            continue

        key = key.strip()
        if key not in CONFIG_TYPES:
            errors.append("Line {} has unknown key '{}'.".format(line_number, key))
            continue

        try:
            values[key] = parse_config_value(key, value)
        except ValueError:
            errors.append(
                "Line {} has invalid value for '{}'.".format(line_number, key)
            )

    return values, errors


def read_config_file(path):
    if not path:
        return "", None

    try:
        with open(str(path), "r") as config_file:
            return config_file.read(), None
    except Exception as error:
        return "", "Could not read config_path: {}".format(error)


def component_config(global_values):
    config = DEFAULT_CONFIG.copy()
    errors = []

    file_text, file_error = read_config_file(global_values.get("config_path", None))
    if file_error:
        errors.append(file_error)

    for text in (
        file_text,
        global_values.get("config", None),
        global_values.get("config_text", None),
    ):
        parsed, parse_errors = parse_config_text(text)
        config.update(parsed)
        errors.extend(parse_errors)

    for key in DEFAULT_CONFIG:
        if key not in global_values or global_values[key] is None:
            continue

        try:
            config[key] = parse_config_value(key, global_values[key])
        except ValueError:
            errors.append("Input '{}' has invalid value.".format(key))

    return config, errors

# --- src/ice_crack/source/geometry.py ---
import Rhino.Geometry as rg


def coerce_planar_brep(geometry, tolerance):
    if isinstance(geometry, rg.Brep):
        brep = geometry.DuplicateBrep()
    elif isinstance(geometry, rg.BrepFace):
        brep = geometry.DuplicateFace(False)
    elif isinstance(geometry, rg.Surface):
        brep = geometry.ToBrep()
    elif isinstance(geometry, rg.Curve):
        if not geometry.IsClosed:
            return None, "Input curve is not closed."

        breps = rg.Brep.CreatePlanarBreps(geometry, tolerance)
        if not breps or len(breps) == 0:
            return None, "Input curve is not planar or cannot make a surface."

        brep = breps[0]
    else:
        return None, "Input must be a planar Surface, Brep, BrepFace, or closed Curve."

    if not brep or brep.Faces.Count == 0:
        return None, "Could not convert input to a Brep."

    face = brep.Faces[0]
    try:
        success, plane = face.TryGetPlane(tolerance)
    except TypeError:
        success, plane = face.TryGetPlane()

    if not success:
        return None, "Input Brep face is not planar."

    return brep, None


def brep_area(brep):
    props = rg.AreaMassProperties.Compute(brep)
    if not props:
        return 0.0

    return props.Area


def normalized_point(curve, value):
    success, parameter = curve.NormalizedLengthParameter(value)
    if not success:
        parameter = curve.Domain.ParameterAt(value)

    return curve.PointAt(parameter)


def outer_boundary_segments(brep):
    face = brep.Faces[0]
    outer_loop = None

    for loop in face.Loops:
        if loop.LoopType == rg.BrepLoopType.Outer:
            outer_loop = loop
            break

    if outer_loop is None:
        return []

    segments = []
    for index, trim in enumerate(outer_loop.Trims):
        edge = trim.Edge
        if edge is None:
            continue

        curve = edge.DuplicateCurve()
        if curve is None:
            continue

        length = curve.GetLength()
        if length <= 0.0:
            continue

        segments.append({
            "index": index,
            "curve": curve,
            "length": length,
        })

    return segments

# --- src/ice_crack/source/utils.py ---
import Rhino


def clamp(value, low, high):
    return max(low, min(high, value))


def get_tolerance(tolerance_override):
    if tolerance_override is not None:
        return float(tolerance_override)

    doc = Rhino.RhinoDoc.ActiveDoc
    if doc:
        return doc.ModelAbsoluteTolerance

    return 0.001

# --- src/ice_crack/source/cracking.py ---
import random

import Rhino.Geometry as rg
from System.Collections.Generic import List



def candidate_side_pairs(segments):
    count = len(segments)
    if count < 2:
        return []

    pairs = []
    for i in range(count):
        for j in range(i + 1, count):
            loop_gap = abs(segments[i]["index"] - segments[j]["index"])
            adjacent = loop_gap == 1 or loop_gap == count - 1
            score = segments[i]["length"] + segments[j]["length"]
            pairs.append((not adjacent, score, segments[i], segments[j]))

    pairs.sort(key=lambda item: (item[0], item[1]), reverse=True)
    return [(item[2], item[3]) for item in pairs]


def build_crack_curves(side_a, side_b, rng, variation, tolerance):
    jitter = clamp(float(variation), 0.0, 1.0) * 0.45
    t_a = clamp(0.5 + rng.uniform(-jitter, jitter), 0.05, 0.95)
    t_b = clamp(0.5 + rng.uniform(-jitter, jitter), 0.05, 0.95)

    pt_a = normalized_point(side_a["curve"], t_a)
    pt_b = normalized_point(side_b["curve"], t_b)

    direction = pt_b - pt_a
    if direction.Length <= tolerance:
        return None, None

    direction.Unitize()

    extension = max(side_a["length"], side_b["length"], pt_a.DistanceTo(pt_b)) * 0.05
    line = rg.Line(pt_a - direction * extension, pt_b + direction * extension)
    display_line = rg.Line(pt_a, pt_b)

    return rg.LineCurve(line), rg.LineCurve(display_line)


def split_once(brep, rng, variation, tolerance):
    segments = outer_boundary_segments(brep)
    pairs = candidate_side_pairs(segments)

    for side_a, side_b in pairs[:10]:
        splitter, display_curve = build_crack_curves(
            side_a,
            side_b,
            rng,
            variation,
            tolerance,
        )
        if splitter is None:
            continue

        splitter_curves = List[rg.Curve]()
        splitter_curves.Add(splitter)
        pieces = brep.Split(splitter_curves, tolerance)
        if not pieces or len(pieces) < 2:
            continue

        valid_pieces = []
        for piece in pieces:
            if brep_area(piece) > tolerance:
                valid_pieces.append(piece)

        if len(valid_pieces) >= 2:
            return valid_pieces, display_curve

    return None, None


def crack_brep(start_brep, smallest_area, depth_limit, variation, random_seed, tolerance):
    rng = random.Random(random_seed)
    pieces = []
    cracks = []
    stack = [(start_brep, 0)]
    attempted = 0

    while stack:
        brep, depth = stack.pop()
        area = brep_area(brep)

        if area <= smallest_area or depth >= depth_limit:
            pieces.append(brep)
            continue

        attempted += 1
        split_pieces, crack = split_once(brep, rng, variation, tolerance)
        if not split_pieces:
            pieces.append(brep)
            continue

        cracks.append(crack)
        for split_piece in split_pieces:
            stack.append((split_piece, depth + 1))

    return pieces, cracks, attempted

# --- src/ice_crack/source/component.py ---


# Grasshopper supplies these names from the component inputs at runtime.
surface = globals()["surface"]
config, config_errors = component_config(globals())


tolerance = get_tolerance(config["tol"])
minimum_area = max(float(config["min_area"]), tolerance)
depth_limit = max(int(config["max_depth"]), 0)

input_brep, error = coerce_planar_brep(surface, tolerance)

if config_errors:
    A = []
    B = []
    C = []
    message = "Config error.\n" + "\n".join(config_errors)
elif error:
    A = []
    B = []
    C = []
    message = error
else:
    cracked_surfaces, crack_curves, split_attempts = crack_brep(
        input_brep,
        minimum_area,
        depth_limit,
        config["crack_variation"],
        config["seed"],
        tolerance,
    )
    areas = [brep_area(piece) for piece in cracked_surfaces]

    A = cracked_surfaces
    B = crack_curves
    C = areas
    message = (
        "Success.\n"
        "Pieces: {}\n"
        "Cracks: {}\n"
        "Split attempts: {}\n"
        "Min area: {:.3f}"
    ).format(
        len(cracked_surfaces),
        len(crack_curves),
        split_attempts,
        minimum_area,
    )
