from __future__ import annotations

import argparse
import ast
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
HEADER_MODULE = "header"
ENTRY_MODULE = "component"


class Component:
    def __init__(self, name: str, source_dir: Path, output: Path):
        self.name = name
        self.source_dir = source_dir
        self.output = output


def discover_components() -> dict[str, Component]:
    components = {}

    # Any src/<name>/source/ folder is treated as one bundleable GH component.
    for source_dir in sorted(SRC.glob("*/source")):
        if not source_dir.is_dir():
            continue

        component_dir = source_dir.parent
        name = component_dir.name
        components[name] = Component(
            name=name,
            source_dir=source_dir,
            output=component_dir / "{}.py".format(name),
        )

    return components


def module_name(path: Path) -> str:
    return path.stem


def source_files(source_dir: Path) -> list[Path]:
    # __init__.py is useful for editor/package behavior, but not for the bundle.
    return [
        path
        for path in sorted(source_dir.glob("*.py"))
        if path.name != "__init__.py"
    ]


def local_dependencies(path: Path, known_modules: set[str]) -> set[str]:
    # Read relative imports such as "from .utils import clamp" so the bundler
    # can place utils.py before the module that depends on it.
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    dependencies = set()

    for node in ast.walk(tree):
        if not isinstance(node, ast.ImportFrom) or node.level != 1:
            continue

        if node.module and node.module in known_modules:
            dependencies.add(node.module)
            continue

        if node.module is None:
            for alias in node.names:
                if alias.name in known_modules:
                    dependencies.add(alias.name)

    dependencies.discard(module_name(path))
    return dependencies


def ordered_parts(source_dir: Path) -> list[Path]:
    parts = source_files(source_dir)
    by_module = {module_name(path): path for path in parts}
    known_modules = set(by_module)
    dependencies = {
        name: local_dependencies(path, known_modules)
        for name, path in by_module.items()
    }

    ordered = []
    remaining = set(by_module)

    # A header module is optional. When present, it usually contains the
    # Grasshopper-facing docstring, so keep it at the very top.
    if HEADER_MODULE in remaining:
        ordered.append(by_module[HEADER_MODULE])
        remaining.remove(HEADER_MODULE)

    # Simple topological sort: repeatedly emit modules whose local dependencies
    # are already emitted. This keeps the generated file executable top-to-bottom.
    while remaining:
        ready = sorted(
            name
            for name in remaining
            if dependencies[name].isdisjoint(remaining)
        )

        if not ready:
            cycle = ", ".join(sorted(remaining))
            raise RuntimeError(
                "Circular local imports in {}: {}".format(source_dir, cycle)
            )

        for name in ready:
            # component.py is the GH entry point. Prefer to run it after all
            # helper functions/classes have been defined.
            if name == ENTRY_MODULE and len(remaining) > 1:
                continue

            ordered.append(by_module[name])
            remaining.remove(name)

        if ready == [ENTRY_MODULE] and ENTRY_MODULE in remaining:
            ordered.append(by_module[ENTRY_MODULE])
            remaining.remove(ENTRY_MODULE)

    return ordered


def bundled_text(path: Path) -> str:
    lines = path.read_text(encoding="utf-8").splitlines()
    bundled_lines = []

    for line in lines:
        # Local relative imports are only needed while editing the modules.
        # In the generated one-file script, those names already exist above.
        if line.strip().startswith("from ."):
            continue

        bundled_lines.append(line)

    return "\n".join(bundled_lines).rstrip()


def bundle_component(component: Component) -> Path:
    parts = ordered_parts(component.source_dir)

    if not parts:
        raise RuntimeError("No source files found in {}".format(component.source_dir))

    sections = [
        "# This file is generated by tools/bundle_ghpython.py.",
        "# Edit src/{}/source/*.py, then run the bundler again.".format(
            component.name
        ),
        "",
    ]

    # Keep source markers in the output so debugging inside Grasshopper still
    # has breadcrumbs back to the editable module.
    for part in parts:
        relative = part.relative_to(ROOT).as_posix()
        text = bundled_text(part)
        sections.append("# --- {} ---".format(relative))
        sections.append(text)
        sections.append("")

    component.output.write_text(
        "\n".join(sections).rstrip() + "\n",
        encoding="utf-8",
    )
    return component.output


def selected_components(
    components: dict[str, Component],
    requested_name: str | None,
) -> list[Component]:
    if requested_name is None:
        return [components[name] for name in sorted(components)]

    if requested_name not in components:
        available = ", ".join(sorted(components)) or "none"
        raise SystemExit(
            "Unknown component '{}'. Available components: {}".format(
                requested_name,
                available,
            )
        )

    return [components[requested_name]]


def main() -> None:
    components = discover_components()

    parser = argparse.ArgumentParser(description="Bundle modular GHPython sources.")
    parser.add_argument(
        "component",
        nargs="?",
        help="Component folder name under src/. If omitted, all components are bundled.",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="List discovered bundleable components.",
    )
    args = parser.parse_args()

    if args.list:
        for name in sorted(components):
            print(name)
        return

    if not components:
        raise SystemExit("No components found. Expected folders like src/name/source/.")

    for component in selected_components(components, args.component):
        output = bundle_component(component)
        print("Bundled {} -> {}".format(component.name, output.relative_to(ROOT)))


if __name__ == "__main__":
    main()
